/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `greatness.t_content_type_info`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `t_content_type_info`;
CREATE TABLE `t_content_type_info` (
    `primary_key` BIGINT NOT NULL AUTO_INCREMENT,
    `_id` INTEGER,
    `create_time` LONGTEXT,
    `modify_time` LONGTEXT,
    `type_english_name` LONGTEXT,
    `type_name` LONGTEXT,
    PRIMARY KEY (`primary_key`)
) CHARSET=utf8;

INSERT INTO `t_content_type_info` (`_id`, `create_time`, `modify_time`, `type_english_name`, `type_name`)
    VALUES
        (1, '2018-09-28 09:00:00', '', 'music', '歌曲');
INSERT INTO `t_content_type_info` (`_id`, `create_time`, `modify_time`, `type_english_name`, `type_name`)
    VALUES
        (2, '2018-09-28 09:00:00', '', 'app', '应用');
INSERT INTO `t_content_type_info` (`_id`, `create_time`, `modify_time`, `type_english_name`, `type_name`)
    VALUES
        (3, '2018-09-28 09:00:00', '', 'location', '地点');
INSERT INTO `t_content_type_info` (`_id`, `create_time`, `modify_time`, `type_english_name`, `type_name`)
    VALUES
        (4, '2018-09-28 09:00:00', '', 'radio_station', '电台');
INSERT INTO `t_content_type_info` (`_id`, `create_time`, `modify_time`, `type_english_name`, `type_name`)
    VALUES
        (5, '2018-09-28 09:00:00', '', 'life_service', '生活服务和食品店等');
INSERT INTO `t_content_type_info` (`_id`, `create_time`, `modify_time`, `type_english_name`, `type_name`)
    VALUES
        (6, '2018-09-28 09:00:00', '', 'commodity', '商品');
