/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `greatness.t_label_type_info`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `t_label_type_info`;
CREATE TABLE `t_label_type_info` (
    `_id` INTEGER NOT NULL,
    `create_time` LONGTEXT,
    `label_english_name` LONGTEXT,
    `label_name` LONGTEXT,
    `modify_time` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `t_label_type_info` (`_id`, `create_time`, `label_english_name`, `label_name`, `modify_time`)
    VALUES
        (1, '2018-09-28 09:00:00', 'other', '其它', '');
INSERT INTO `t_label_type_info` (`_id`, `create_time`, `label_english_name`, `label_name`, `modify_time`)
    VALUES
        (2, '2018-09-28 09:00:00', 'content_error', '内容错误，需要修正', '');
INSERT INTO `t_label_type_info` (`_id`, `create_time`, `label_english_name`, `label_name`, `modify_time`)
    VALUES
        (3, '2018-09-28 09:00:00', 'content_name_extension', '内容名扩展', '');
INSERT INTO `t_label_type_info` (`_id`, `create_time`, `label_english_name`, `label_name`, `modify_time`)
    VALUES
        (4, '2018-09-28 09:00:00', 'entertainment', '电影、电视剧、动漫等娱乐类词典', '');
INSERT INTO `t_label_type_info` (`_id`, `create_time`, `label_english_name`, `label_name`, `modify_time`)
    VALUES
        (5, '2018-09-28 09:00:00', 'song', '歌曲名', '');
INSERT INTO `t_label_type_info` (`_id`, `create_time`, `label_english_name`, `label_name`, `modify_time`)
    VALUES
        (6, '2018-09-28 09:00:00', 'broadcast', '电台名(喜马拉雅中的电台)', '');
INSERT INTO `t_label_type_info` (`_id`, `create_time`, `label_english_name`, `label_name`, `modify_time`)
    VALUES
        (7, '2018-09-28 09:00:00', 'food__store', '食品店名、外卖店名', '');
INSERT INTO `t_label_type_info` (`_id`, `create_time`, `label_english_name`, `label_name`, `modify_time`)
    VALUES
        (8, '2018-09-28 09:00:00', 'life_service', '生活服务方面如理发、买衣服等', '');
INSERT INTO `t_label_type_info` (`_id`, `create_time`, `label_english_name`, `label_name`, `modify_time`)
    VALUES
        (9, '2018-09-28 09:00:00', 'commodity', '商品如衣服、鞋子等', '');
