/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `greatness.t_statement_info`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `t_statement_info`;
CREATE TABLE `t_statement_info` (
    `_id` VARBINARY(12) NOT NULL,
    `content` LONGTEXT,
    `content_name_extend` LONGTEXT,
    `content_type` INTEGER,
    `create_time` LONGTEXT,
    `error_correction` LONGTEXT,
    `is_processed` INTEGER,
    `label_type` INTEGER,
    `modify_time` LONGTEXT,
    `user_id` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADDD31DA37CB2DF47302B7', '难回头', '', 1, '2018-09-28 15:50:09', '', 1, 4, '2018-09-30 15:07:55', '5');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBAD', '走着走着就散了', '', 0, '2018-09-28 16:28:16', '', 0, 0, '2018-09-30 15:08:01', '5');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBAE', '浪人琵琶', '', 0, '2018-09-28 16:28:16', '', 0, 0, '2018-09-28 18:00:01', '5');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBAF', '由我们主宰', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '5');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBB0', '默', '', 0, '2018-09-28 16:28:16', '', 0, 0, '2018-09-28 18:09:37', '5');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBB1', '嘴巴嘟嘟', '', 0, '2018-09-28 16:28:16', '', 0, 0, '2018-09-28 17:07:08', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBB2', '不爱我就拉倒', '', 0, '2018-09-28 16:28:16', '', 0, 0, '2018-09-28 18:11:56', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBB3', '答案', '', 0, '2018-09-28 16:28:16', '', 0, 0, '2018-09-28 17:17:35', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBB4', '讲真的', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBB5', 'Girls', '', 0, '2018-09-28 16:28:16', '', 0, 0, '2018-09-28 18:11:36', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBB6', '陷阱', '', 0, '2018-09-28 16:28:16', '', 0, 0, '2018-09-28 18:11:31', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBB7', '醉千年', '', 0, '2018-09-28 16:28:16', '', 0, 0, '2018-09-28 18:11:42', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBB8', '如果没有你', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBB9', 'Dont Go Breaking My Heart', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBBA', '梦中人', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBBB', '卡路里', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBBC', '2013深港最新中文串烧大碟', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBBD', '我变了 我没变', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBBE', '叹云兮', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBBF', 'For You', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBC0', '彩虹下面', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBC1', '当每颗星星', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBC2', 'Seve', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBC3', '学猫叫', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBC4', 'Something Just Like This', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBC5', 'Darkside', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBC6', '我已经爱上你', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBC7', '念念不忘', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBC8', '我的将军啊', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBC9', 'Faded', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBCA', '你把我灌醉', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBCB', '往后余生', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBCC', 'The Spectre', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBCD', '因为遇见你2018版', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBCE', '夜是秋月明', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBCF', '我们终究是错过', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBD0', '中国魂', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBD1', '年轮 ', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBD2', '我的滑板鞋2016', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBD3', 'Pull Up', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBD4', '花桥流水', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBD5', '谢谢你的爱', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBD6', '需要人陪', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBD7', '彩霞回来吧', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBD8', '私奔到月球', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBD9', '时间飞行', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBDA', '小可爱与小领带', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBDB', '高原蓝', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBDC', '对不起', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBDD', '写给妹妹的歌', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBDE', '独上西楼', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBDF', '爱如意', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBE0', '在树上唱歌', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBE1', '九月的故事', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBE2', '天冷就回来2016', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBE3', '牧马城市', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBE4', '寻', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBE5', '原香草', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBE6', 'Dinero', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBE7', '再也没有', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBE8', '画沙', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBE9', '钟无艳', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBEA', '嘟啊嘟啊', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBEB', '一封情书', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBEC', '明明就', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBED', 'There for You', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBEE', '山茶花', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBEF', '爱与痛的边缘', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBF0', '只想一生跟你走', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBF1', '空城', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBF2', '谢谢你', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBF3', 'Closer', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBF4', '山海', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBF5', '乌苏里船歌', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBF6', '新写的旧歌', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBF7', '吉祥的酥油灯', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBF8', '儿歌三百首', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBF9', '父子', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBFA', '我爱洗澡', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBFB', '心中的草原', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBFC', '如果爱下去', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBFD', '难忘初恋的情人', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBFE', '黑色幽默', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDBFF', '风雨彩虹铿锵玫瑰', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC00', 'Oops', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC01', '下一个天亮', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC02', 'Lemon', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC03', '爱情向前进', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC04', '风再起时', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC05', '月亮升起来', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC06', '一个小心愿', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC07', '渐渐', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC08', '国旗国旗多美丽', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC09', '比我幸福', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC0A', '心痛2015', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC0B', '会过去的', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC0C', '午夜唱情歌', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC0D', '最佳损友', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC0E', '分手在那个秋天', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC0F', '雨一直下', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
INSERT INTO `t_statement_info` (`_id`, `content`, `content_name_extend`, `content_type`, `create_time`, `error_correction`, `is_processed`, `label_type`, `modify_time`, `user_id`)
    VALUES
        (x'5BADE620DA37CB2AB86CDC10', '等我遇见你', '', 0, '2018-09-28 16:28:16', '', 0, 0, '', '');
