/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `greatness.t_user_info`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `t_user_info`;
CREATE TABLE `t_user_info` (
    `_id` INTEGER NOT NULL,
    `create_time` LONGTEXT,
    `email` LONGTEXT,
    `is_admin` LONGTEXT,
    `login_name` LONGTEXT,
    `nick_name` LONGTEXT,
    `password` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (1, '2018-09-28 09:00:00', 'sktt1@sina.com', 'N', 'faker', NULL, '8c5ff676f2e9eafaaf04df210b2191b7');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (2, '2018-09-28 09:00:00', 'root@vivo.com', 'N', 'root', 'root', '4f5fba03a86607a215fe91bd47735689');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (3, '2018-09-28 09:00:00', 'chen.chen@vivo.com', 'N', 'chenchen', '陈晨', '3450e5a2aa19fdf94c0ccd2781f5b633');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (4, '2018-09-28 09:00:00', 'test@test.com', 'N', 'one', 'one', '290859489353ff4112052b089efa5c0f');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (5, '2018-09-28 09:00:00', 'user014@qq.com', 'N', 'user014', 'user014', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (6, '2018-09-28 09:00:00', 'user013@qq.com', 'N', 'user013', 'user013', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (7, '2018-09-28 09:00:00', 'user012@qq.com', 'N', 'user012', 'user012', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (8, '2018-09-28 09:00:00', 'user011@qq.com', 'N', 'user011', 'user011', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (9, '2018-09-28 09:00:00', 'user010@qq.com', 'N', 'user010', 'user010', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (10, '2018-09-28 09:00:00', 'user009@qq.com', 'N', 'user009', 'user009', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (11, '2018-09-28 09:00:00', 'user008@qq.com', 'N', 'user008', 'user008', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (12, '2018-09-28 09:00:00', 'user007@qq.com', 'N', 'user007', 'user007', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (13, '2018-09-28 09:00:00', 'user006@qq.com', 'N', 'user006', 'user006', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (14, '2018-09-28 09:00:00', 'user005@qq.com', 'N', 'user005', 'user005', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (15, '2018-09-28 09:00:00', 'user004@qq.com', 'N', 'user004', 'user004', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (16, '2018-09-28 09:00:00', 'user003@qq.com', 'N', 'user003', 'user003', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (17, '2018-09-28 09:00:00', 'user002@qq.com', 'N', 'user002', 'user002', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (18, '2018-09-28 09:00:00', 'user001@qq.com', 'N', 'user001', 'user001', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (19, '2018-09-28 09:00:00', 'user015@qq.com', 'N', 'user015', 'user015', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (20, '2018-09-28 09:00:00', 'user016@qq.com', 'N', 'user016', 'user016', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (21, '2018-09-28 09:00:00', 'user017@qq.com', 'N', 'user017', 'user017', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (22, '2018-09-28 09:00:00', 'user018@qq.com', 'N', 'user018', 'user018', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (23, '2018-09-28 09:00:00', 'user019@qq.com', 'N', 'user019', 'user019', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (24, '2018-09-28 09:00:00', 'user020@qq.com', 'N', 'user020', 'user020', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (25, '2018-09-28 09:00:00', 'user021@qq.com', 'N', 'user021', 'user021', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (26, '2018-09-28 09:00:00', 'user022@qq.com', 'N', 'user022', 'user022', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (27, '2018-09-28 09:00:00', 'user023@qq.com', 'N', 'user023', 'user023', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (28, '2018-09-28 09:00:00', 'user024@qq.com', 'N', 'user024', 'user024', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (29, '2018-09-28 09:00:00', 'user025@qq.com', 'N', 'user025', 'user025', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (30, '2018-09-28 09:00:00', 'user026@qq.com', 'N', 'user026', 'user026', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (31, '2018-09-28 09:00:00', 'user027@qq.com', 'N', 'user027', 'user027', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (32, '2018-09-28 09:00:00', 'user028@qq.com', 'N', 'user028', 'user028', '069fca38c171e645bc88e294ea41f9f8');
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (33, '2018-09-28 09:00:00', 'ming@qq.com', 'N', 'ming', NULL, 'fa94d2a7af64896cbe624138db529f7f');
/* CONVERSION WARNING!
 *     - Truncation to NULL while exporting field at '_id' of MongoDB type 'ObjectId' to SQL column '_id' of type 'INTEGER'!
*/
INSERT INTO `t_user_info` (`_id`, `create_time`, `email`, `is_admin`, `login_name`, `nick_name`, `password`)
    VALUES
        (0, '2018-09-28 09:00:00', 'admin@qq.com', 'Y', 'admin', NULL, 'c0e024d9200b5705bc4804722636378a');
